### PR TITLE
allow date suffixes in upgrade script

### PR DESCRIPTION
**Pull request by jsonar-cpapke**
Closes https://onejira.imperva.com/browse/SD-1379

### CODE REVIEW

**Review by gabibeyo — CHANGES_REQUESTED** [review]
Can't see that the Actions did run.

**Comment by jsonar-cpapke** [comment]
Job has been run and passed

**Review by gabibeyo — APPROVED** [review]

**Comment by gabibeyo** [comment]
Approved by me, the PR is awaiting @jagdeep-sonar

**Review by jagdeep-sonar — APPROVED** [review]
ok.

**Pull request merged**
