### PR TITLE
Updating the sonar versions

### PR DESCRIPTION
**Pull request by jagdeep-sonar**

### CODE REVIEW

**Review by darya-abdollahzadeh — COMMENTED** [review]
👍

**Review by darya-abdollahzadeh — APPROVED** [review]
👍

**Comment by lindanasredin** [comment]
@jagdeep-sonar Please separate support for major version from patch version. Patch version can be merged to dev immediately while merging major version is a more complex process and you have to wait for all the DSF teams to add 
 their support.

**Comment by lindanasredin** [comment]
Also, 3 of the 5 actions failed on this branch. All actions should be green before we approve.

**Comment by jagdeep-sonar** [comment]
Ok Linda.. i will separate support for major version from patch version. 
 and how will I get to know if all the DSF teams have added their support for major version?

**Comment by lindanasredin** [comment]
Thank Jagdeep. My team is responsible for releasing an eDSF Kit version when a new DSF version is released, so once you created the PR and saw that the actions passed, your job is done, unless we find issues with the integrations between Sonar, DAM and DRA later. Please take a look at the procedure that my team does here: https://docs.google.com/document/d/1vNp3P6JH9QAsHtnNqpkFtTLMZD7sZT6eeNsu8lK2CVo

**Comment by jagdeep-sonar** [comment]
Ok Linda. Got it. I will close this PR and raise separate PRs for major and patch version. Thank you.

**Pull request closed without merging**
