### PR TITLE
update default ami to latest rhel8 image

### PR DESCRIPTION
**Pull request by jsonar-cpapke**
Closes https://onejira.imperva.com/browse/EDSF-712 ticket was moved to sonar devops board https://onejira.imperva.com/browse/SD-1376

### CODE REVIEW

**Review by eytannnaim — APPROVED** [review]

**Comment by jsonar-cpapke** [comment]
@eytannnaim when will the tests be fixed?

**Comment by eytannnaim** [comment]
> @eytannnaim when will the tests be fixed?

I'm sorry. Ill try to clean the environment now.

Update: it seems like linda fixed it.

**Comment by jsonar-cpapke** [comment]
It seems like the Terraform Cloud builds are still failing, should I just merge this anyway?

**Comment by eytannnaim** [comment]
> It seems like the Terraform Cloud builds are still failing, should I just merge this anyway?

Yes. The fix was to disable terraform cloud.

**Comment by jsonar-cpapke** [comment]
@eytannnaim looks like I accidentally merged to master instead of dev, can you revert that?

**Comment by eytannnaim** [comment]
Done

> @eytannnaim looks like I accidentally merged to master instead of dev, can you revert that?

**Pull request merged**
