### PR TITLE
Update password restriction, fix validation

### PR DESCRIPTION
**Pull request by jsonar-cpapke**

### CODE REVIEW

**Review by lindanasredin — APPROVED** [review]

**Comment by jsonar-cpapke** [comment]
@lindanasredin can this be merged?

**Comment by lindanasredin** [comment]
@jsonar-cpapke yes please, I approved last week and wrote it in an email. Thanks

**Comment by jsonar-cpapke** [comment]
I don't really know your release schedule or what you want in each release, so I'm not sure when I should be merging my PRs normally (or if I should be even).

**Comment by lindanasredin** [comment]
@jsonar-cpapke fair point, I understand now that it is not enough for me to approve a PR or say that I approved it, next time I will explicitly request that you merge the PR.
I believe that in time, as we get used to each other, we will work more smoothly.

**Pull request merged**
