### PR TITLE
Add all published sonar versions

### PR DESCRIPTION
**Pull request by jsonar-cpapke**
None of these have been uploaded yet (to be done). And no examples have been updated yet for this code.

JIRA : https://onejira.imperva.com/browse/SD-1045

### CODE REVIEW

**Review by lindanasredin — APPROVED** [review]

**Comment by lindanasredin** [comment]
I found a bug in our github actions thanks to this PR - when you created the PR, no actions were triggered, which is weird.
It's because of this line in the yamls:
    'modules/aws/core/*' 
It should be:
    'modules/aws/core/**'
I will fix it now, but you can merge this PR to dev regardless, the actions will run in the nightly automation.
Thanks.

**Comment by jsonar-cpapke** [comment]
We are waiting on S3 uploads before merging this.

**Review by lindanasredin — CHANGES_REQUESTED** [review]
Please split support for 4.14 from support for the other patches. This way we can merge the patches PR, while the 4.14 PR will await the rest of the DSF teams and I will merge all 3 together to dev. Also, in the 4.14 PR, please also update the examples and the README, which are items 4 and 5 in our document (in step 2). Thanks.

**Comment by jsonar-cpapke** [comment]
The idea was to add the support here, but not the defaults until everyone else was read. But I'll remove it.

**Review by sivan-hajbi-imperva — APPROVED** [review]

**Review by lindanasredin — APPROVED** [review]

**Comment by lindanasredin** [comment]
If we add support for 4.14 in the modules but don't update the examples, then the automation tests won't run with 4.14. It means that we offer 4.14 to our customers without making sure the out-of-the-box examples we offer them work with the new version.
Approved.
Please merge the PR to dev and follow up with the github actions which are triggered following merge to dev to make sure they pass. Thanks.

**Pull request merged**
