### PR TITLE
cleanup security group loop

### PR DESCRIPTION
**Pull request by jsonar-cpapke**

### CODE REVIEW

**Review by eytannnaim — APPROVED** [review]
Does it fix some problems or is it just making the code more aesthetic?

Anyway, looks good to me. Please make sure "terraform plan" works when you pass in `security_group_ids` since it caused us some problems in the past.

**Comment by jsonar-cpapke** [comment]
Without this, `azurerm_network_security_group` is created regardless if there are any security group ids or not.

**Comment by eytannnaim** [comment]
> Without this, `azurerm_network_security_group` is created regardless if there are any security group ids or not.

If I recall correctly that's on purpose. Terraform needs to know on plan phase what resources will be created. And in this case, it couldn't know it in the plan phase. Please verify your fix works when passing a `var.security_group_ids` from outside

**Comment by jsonar-cpapke** [comment]
What do you mean? If I'm passing in `security_group_ids`, it's because I don't want terraform to create a security group for me. The `dsf_base_sg` is only used if `security_group_ids` is length zero anyway, so there's no reason to create it if we pass in the security group ids.

```
security_group_id = length(var.security_group_ids) == 0 ? azurerm_network_security_group.dsf_base_sg[0].id : var.security_group_ids[0]
```

**Comment by eytannnaim** [comment]
I see that. I didn't say it's perfect. I just said that terraform needs to know during the `plan` phase about all resources that it is going to create on the `apply` phase. I believe there was some problem that the `plan` phase wasn't sure if this sg is going to be created or not. And that's why the condition is not on the security group. If you can fix that - great.

I only meant that you should verify that passing external sg works (I believe it might not work. But maybe I either mistaken or this gap was fixed since then)

**Comment by jsonar-cpapke** [comment]
Yes, I am passing in `security_group_ids` when testing, and this change makes sure that we aren't creating an unused extra security group.

**Comment by jsonar-cpapke** [comment]
Are we good to merge this then?

**Comment by darya-abdollahzadeh** [comment]
> Are we good to merge this then?

@jsonar-cpapke I see the thumbs up - let's process and merge this (thanks Eytan for reviewing)

**Pull request merged**
