### PR TITLE
use the existing mongo shell binary

### PR DESCRIPTION
**Pull request by jsonar-cpapke**
https://onejira.imperva.com/browse/SD-1255

### CODE REVIEW

**Comment by lindanasredin** [comment]
@jsonar-cpapke all actions failed. There are 3 options: 1. The code broke the actions - need to fix the code. 2. The failures are not related to the code and you re-run until you get green. 3. The failures are not related to the code and you write us a comment that the failures are not related to you. Please don't assign us as reviewers before you do this. Thanks.

**Comment by jsonar-cpapke** [comment]
I had re-run the AWS build that failed before adding reviewers.

**Comment by jsonar-cpapke** [comment]
I'm not able to replicate the new errors, and I can't access the machines that have the error:

```
Error: remote-exec provisioner error

  with module.hub_dr[0].module.hub_instance.null_resource.readiness[0],
  on ../../../../modules/aws/sonar-base-instance/userdata.tf line 58, in resource "null_resource" "readiness":
  58:   provisioner "remote-exec" {

error executing "/tmp/terraform_1701963393.sh": Process exited with status 1

Error: remote-exec provisioner error

  with module.hub_main[0].module.hub_instance.null_resource.readiness[0],
  on ../../../../modules/aws/sonar-base-instance/userdata.tf line 58, in resource "null_resource" "readiness":
  58:   provisioner "remote-exec" {

error executing "/tmp/terraform_1946651670.sh": Process exited with status 1
```

**Comment by lindanasredin** [comment]
There's a trick to finding the root cause error in the action log, I will try to catch you today to show you in zoom, and in the meantime, this is the error I saw in one of the actions:
`module.hub_main[0].module.hub_instance.null_resource.readiness[0] (remote-exec): @(shell):1:1
module.hub_main[0].module.hub_instance.null_resource.readiness[0] (remote-exec): Cloud-init v. 21.1-15.el8 running 'modules:final' at Mon, 22 Apr 2024 18:10:29 +0000. Up 10.79 seconds.
Warning: b_main[0].module.hub_instance.null_resource.readiness[0] (remote-exec): 2024-04-22 18:16:25,154 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
Warning: b_main[0].module.hub_instance.null_resource.readiness[0] (remote-exec): 2024-04-22 18:16:25,154 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3.6/site-packages/cloudinit/config/cc_scripts_user.py'>) failed
module.hub_main[0].module.hub_instance.null_resource.readiness[0] (remote-exec): Cloud-init v. 21.1-15.el8 finished at Mon, 22 Apr 2024 18:16:25 +0000. Datasource DataSourceEc2Local.  Up 366.81 seconds

module.hub_main[0].module.hub_instance.null_resource.readiness[0] (remote-exec): status: error`

Regarding access to the machines, in general, the SSH keys are available in the action if you click on Summary and go the bottom of the page:

image

However, these are available only in nightly runs on dev and master branches for next 24 hours, until the next nightly runs.
For actions which are not nightly, the setups are destroyed at the end of the action run as you can see in the action flow.

**Comment by jsonar-cpapke** [comment]
Current failures seem unrelated to this change (systemd file not starting correctly)

**Comment by lindanasredin** [comment]
This action failed on HADR:
https://github.com/imperva/dsfkit/actions/runs/8820187981/job/24213205540

module.agentless_gw_hadr[0].null_resource.exec_hadr_main (remote-exec):                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
module.agentless_gw_hadr[0].null_resource.exec_hadr_main (remote-exec):   File "/imperva/apps/jsonar/apps/4.15.0.10.0/lib/python3.11/subprocess.py", line 571, in run
module.agentless_gw_hadr[0].null_resource.exec_hadr_main (remote-exec):     raise CalledProcessError(retcode, process.args,
module.agentless_gw_hadr[0].null_resource.exec_hadr_main (remote-exec): subprocess.CalledProcessError: Command '['sudo', '/bin/systemctl', 'start', 'dsfdiagnosticsagent.service']' returned non-zero exit status 1.

**Comment by jsonar-cpapke** [comment]
Seems unrelated, worked after a re-run.

**Comment by lindanasredin** [comment]
Yes it is probably unrelated, but it is something that fails the automation, prevents it from being reliable and wastes time and resources. I will approve this PR, but can you please suggest a plan on how to get this issue fixed once and for all? Maybe consult with @darya-abdollahzadeh

**Comment by jsonar-cpapke** [comment]
@lindanasredin can you please approve the PR then?

**Comment by darya-abdollahzadeh** [comment]
> Yes it is probably unrelated, but it is something that fails the automation, prevents it from being reliable and wastes time and resources. I will approve this PR, but can you please suggest a plan on how to get this issue fixed once and for all? Maybe consult with @darya-abdollahzadeh

Thanks Linda for reviewing this PR. We could not replicate the issue in question, and therefore we created a placeholder to monitor and see if we can reproduce. https://onejira.imperva.com/browse/SD-1251.

**Comment by lindanasredin** [comment]
Thanks @darya-abdollahzadeh. Many issues happen intermittently and can't be easily replicated so I don't think we should rely on replicating issues in another automation system to solve them. This is one of the purposes of this automation. Can you please show Guilherme the log of the automation? Maybe it is enough for him to understand the problem. Also, when a failure occurs in the nightly automation, the environment is not destroyed until the next nightly (24 hours) to allow investigating the logs. I also created a new PR in which a developer can run an action manually and request that the destroy of the environment be delayed: https://github.com/imperva/dsfkit/pull/407. If you have more ideas on how we can investigate issues in-place without needing to replicate them, I would love to hear. Thanks.

**Review by lindanasredin — APPROVED** [review]

**Review by jagdeep-sonar — APPROVED** [review]
Ok.

**Pull request merged**
